### ISSUE TITLE
using patch or other methods with HttpURLConnection

### ISSUE THREAD

**Issue by jdamick** [Netflix/feign#134]
What's the thought on applying a workaround similar to jersey to use PATCH or other methods to HttpURLConnection?   

see:
https://github.com/jersey/jersey/blob/master/core-client/src/main/java/org/glassfish/jersey/client/HttpUrlConnector.java#L388

from: http://java.net/jira/browse/JERSEY-639

**Comment by adriancole** [comment]
I'm fine with it. Surprised we haven't added an okhttp or netty adaptor!

**Comment by jdamick** [comment]
may just use okhttp, need to think about that - thanks.
