### ISSUE TITLE
[question] How to use Feign with a JAX-RS interface defining jaxrs.Response as return types

### ISSUE THREAD

**Issue by bertrand-quenin** [Netflix/feign#188]
Hi,

I'm using Feign with a JAX-RS interface using JAX-RS Response return types (not feign.Response). 
For instance:

```java
@Path("/users")
@Produces(MediaType.APPLICATION_JSON)
public interface UserContract {
    @POST
    @Path("/")
    @Consumes(MediaType.APPLICATION_JSON)
    public Response create(User user);

    ...
```

When using feign and calling the "create" method, it seems that feigns tries to deserialize the jaxrs.Response object from the HTTP reponse.

Well it makes sense since it's the return type but it's obviously not what I expect. What would be the best way to handle jaxrs.Response type with feign ?

Thanks

**Comment by adriancole** [comment]
Would need some thought. Maybe a custom decoder I suppose.

**Comment by adriancole** [comment]
Here's a workaround.. wrap your real decoder with this.

```java
final class ResponseDecoder implements Decoder {
  private final Decoder delegate;

  ResponseDecoder(Decoder delegate) {
    this.delegate = delegate;
  }

  @Override
  public Object decode(Response response, Type type) throws IOException {
    if (jaxrs.Response.class.equals(type)) {
      // construct and return.
    }
    return delegate.decode(response, type);
  }
}
```

**Comment by bertrand-quenin** [comment]
Thanks, that's basically the solution I had, just wanted a confirmation.

**Comment by AjitDas** [comment]
@bquenin @adriancole do you have sample to share how you converted feign Response to jaxrs Response with the entity object set into it. 

Thanks a lot in advance

```
import java.io.IOException;
import java.lang.reflect.Type;
import java.util.Collection;
import java.util.Map;

import javax.ws.rs.core.Response.ResponseBuilder;

import feign.Response;
import feign.codec.Decoder;

public class ResponseDecoder implements Decoder {

	private final Decoder delegate;

	public ResponseDecoder(Decoder delegate) {
		this.delegate = delegate;
	}

	@Override
	public Object decode(Response response, Type type) throws IOException {
		
		if (javax.ws.rs.core.Response.class.equals(type)) {
			// construct and return.
			ResponseBuilder responseBuilder = javax.ws.rs.core.Response
					.status(response.status())
					.entity(...................); // need to get the mapped entity object here , calling delegate.decode(response, type) won't help since the type is javax.ws.rs.core.Response here
			for(Map.Entry<String,Collection<String>> entry:response.headers().entrySet()) {
				responseBuilder.header(entry.getKey(), entry.getValue());
			}
			return responseBuilder.build();
		}
		return delegate.decode(response, type);
	}
}
```

**Comment by mattmadhavan** [comment]
Helo,
I have been stuck on this same issue for two days. Can any of you share the source code please?

**Comment by mattmadhavan** [comment]
Sorry figure it out! Got my entity like below!

`	@Override
	public Object decode(Response response, Type type) throws IOException {
		
		if (javax.ws.rs.core.Response.class.equals(type)) {
			
			String bodyStr = IOUtils.toString(response.body().asInputStream(), Charsets.UTF_8);
			// construct and return.
			ResponseBuilder responseBuilder = javax.ws.rs.core.Response
					.status(response.status())
					.entity(bodyStr); // need to get the mapped entity object here , calling delegate.decode(response, type) won't help since the type is javax.ws.rs.core.Response here
			for(Map.Entry<String,Collection<String>> entry:response.headers().entrySet()) {
				responseBuilder.header(entry.getKey(), entry.getValue());
			}
			return responseBuilder.build();
		}
		return delegate.decode(response, type);
	}`

**Comment by velo** [comment]
That could be included on the jaxrs module...  if you are interest in making a PR, I can review it.
