### ISSUE TITLE
ErrorDecoder should have access to Decoder

### ISSUE THREAD

**Issue by sfussenegger** [Netflix/feign#194]
some APIs send encoded data along with error codes, e.g. explaining the error. In such cases, it would be the decoder much easier if the Decoder would be passed along with the methodKey and response (and probably type)

**Comment by adriancole** [comment]
Makes sense, but since users pass feign the decoder, couldn't they also
pass it to their error decoder?

**Comment by sfussenegger** [comment]
It's certainly another option. However, coming from spring-cloud, it's less obvious as the decoder isn't created by the user.

**Comment by adriancole** [comment]
Oh I see..

I wonder if spring cloud binds the decoder. If so, you could inject it in
your error decoder (saving the complexity of another param)..

**Comment by sfussenegger** [comment]
As I said it's less obvious since it's not documented and probably subject to change anytime. Anyway, I just thought it would fit the style better, but that comes down to a matter of taste. Backward compatibility certainly favors injecting though.

**Comment by adriancole** [comment]
yeah it is the compatibility that bites.. I mean one thing retrofit used to
do was to expose the decoder as a part of the response type. since, they've
actually deleted their response type :P

**Comment by adriancole** [comment]
All that said, we could reduce the non-obviousness with an example.
Ex. make a error decoder in the github example?
https://developer.github.com/v3/#client-errors

**Comment by sfussenegger** [comment]
sounds great

**Comment by adriancole** [comment]
ok I will give this a go and complete before 4.4

**Comment by adriancole** [comment]
unless you'd like to! :)

**Comment by sfussenegger** [comment]
there you go
