### ISSUE TITLE
How to create request params based on Map? 

### ISSUE THREAD

**Issue by beku8** [Netflix/feign#216]
Is there a way to dynamically map request params using Map?
E.g instead of this
```@RequestLine("GET /?foo={bar}") Result list(@Param("bar") String bar);```
something like
```@RequestLine("GET /") Result list(@Param Map params);```

This would be great, because now I don't have overload the same method over & over.

**Comment by adriancole** [comment]
Should be possible with a custom Expander. At the bottom of this file is an
example you can play with

https://github.com/Netflix/feign/blob/master/core/src/test/java/feign/DefaultContractTest.java

**Comment by beku8** [comment]
ok thanks

**Comment by adriancole** [comment]
And if that doesn't work for some reason, you can make an Encoder which
definitely will. Goos luck!
