### ISSUE TITLE
documentation: only 1 example

### ISSUE THREAD

**Issue by torstenwerner** [Netflix/feign#218]
Hi,

README.md tells us that "You can find several examples in the test tree" but there is exactly 1 example below https://github.com/Netflix/feign/tree/master/core/src/test/java/feign/examples . Either someone deleted the examples or the documentation is not fully correct.

Regards,
Torsten

**Comment by spencergibb** [comment]
https://github.com/Netflix/feign/tree/master/example-github and https://github.com/Netflix/feign/tree/master/example-wikipedia

**Comment by adriancole** [comment]
Good point. This is out of date. We used to have more examples in the test
tree, then we settled on a couple outside of it. If there's something you
are looking for, let us know. Otherwise I suspect action to take here is to
fix the README. Sound good?

**Comment by torstenwerner** [comment]
Yes that sounds good.

**Comment by adriancole** [comment]
okiedokie. click refresh
