### ISSUE TITLE
RibbonClient mangles url when service id matches another part of the URI

### ISSUE THREAD

**Issue by spencergibb** [Netflix/feign#221]
In [RibbonClient.java#L66](https://github.com/Netflix/feign/blob/master/ribbon/src/main/java/feign/ribbon/RibbonClient.java#L66), when the service id happens to match something else on the url, the url ends up mangled.  See https://github.com/spring-cloud/spring-cloud-netflix/issues/305

`http://questions/questions/answered/123` becomes `http:////answered/123`, when it should be `http:///questions/answered/123`

**Comment by adriancole** [comment]
pushed release tag. should be out in a bit https://github.com/Netflix/feign/tree/v8.1.1
