### ISSUE TITLE
Space in URL parameter (encoding)

### ISSUE THREAD

**Issue by matbhe** [Netflix/feign#225]
The RequestTemplate encodes all spaces in URL parameters as "+" instead of "%20". Parameters in the URL should not be encoded with the URLEncoder (https://www.ietf.org/rfc/rfc2396.txt).

Example:
http://example.com/api/{value1}?key={value2}
value1=ABC 123
value2=XYZ 123
results in
http://example.com/api/ABC+123?key=XYZ+123
According to rfc2396 the value1 should be encoded as ABC%20123
http://example.com/api/ABC%20123?key=XYZ+123

A cheap fix would be the following change on Line 193 in class RequestTemplate:
String resolvedUrl = expand(url.toString(), encoded).replace("%2F", "/"); 
to 
String resolvedUrl = expand(url.toString(), encoded).replace("%2F", "/")**.replace("+", "%20");**

**Comment by adriancole** [comment]
I've seen a cheap fix like this before :) Would you like to try? update RequestTemplate and RequestTemplateTest?

**Comment by ajeeshpu** [comment]
I am usin JaxRsContract with feign, but it still looks like the query parameters  are encoded with plus (+) for space.

I am on Feign: `8.15.1`

The `JaxRsContract` uses data.template().query(name, query) that still goes through the UrlEncoder that encodes space as `+`.
```
private static String urlEncode(Object arg) {
    try {
      return URLEncoder.encode(String.valueOf(arg), UTF_8.name());
    } catch (UnsupportedEncodingException e) {
      throw new RuntimeException(e);
    }
  }
```
