### ISSUE TITLE
Why is the '/' character (%2F) decoded in the RequestTemplate ?

### ISSUE THREAD

**Issue by MaximeGaudin** [Netflix/feign#227]
The RequestTemplate's method resolve does not allow to have encoded '/' : 
`String resolvedUrl = expand(url.toString(), encoded).replace("%2F", "/");`

Why is that ? How can I send encoded slash an other way ?

**Comment by adriancole** [comment]
Good question, you can do this now, but only if you make a target in the feign package.

#228 makes it easier. Will merge and release 8.2 shortly.

**Comment by MaximeGaudin** [comment]
Awesome ! Thanks for the quick response and the incredible work  :)

**Comment by adriancole** [comment]
we aim to please! thanks for contributing feature ideas!
