### ISSUE TITLE
URLEncode string parameters

### ISSUE THREAD

**Issue by jerry4** [Netflix/feign#235]
I'm not sure if I'm missing something, but why doesn't feign url encode string parameters automatically?
eg:  
```
@RequestLine("GET /{someString}")
String foo(@Param("someString") String someString)
```
It seems like feign should automatically encode the string for me, but instead I get a 404 calling host/foo/some/str
`proxy.foo("some/str");`

Thanks,
Jerry

**Comment by NitishDeshpande** [comment]
How did u solve this issue?

**Comment by NZhuravlev** [comment]
@jerry4 why closing?

**Comment by tony-cui** [comment]
may this link helps https://stackoverflow.com/questions/43889140/feign-url-encode-path-params
