### ISSUE TITLE
end-of-input exception in the JacksonDecoder

### ISSUE THREAD

**Issue by bcrowcs** [Netflix/feign#247]
If an null/empty stream is returned in a body where a JacksonDecoder is used, you can receive an error when the ObjectMapper attempts to read the inputStream value on line 55. 
A quick check to inputSteam.available > 0 seems to stop this problem for me.

**Comment by adriancole** [comment]
wanna give a go at a pull request? I can help merge/release it

**Comment by bcrowcs** [comment]
Just put the wrong issue number on the pull request. It is attached to 246 instead of 247.
