### ISSUE TITLE
Setting logLevel() to BASIC breaks functionality in 8.6.0

### ISSUE THREAD

**Issue by maximdim** [Netflix/feign#250]
Following works in 8.5.0 but not in 8.6.0, but if I change to .logLevel(Level.FULL) it works with 8.6.0 too.

    client = Feign.builder()
        .encoder(new JacksonEncoder(mapper))
        .decoder(new JacksonDecoder(mapper))
        .client(new feign.okhttp.OkHttpClient(okHttpClient))
        .retryer(new Retryer.Default(0, 0, 1)) // do not retry calls
        .logger(new Slf4jLogger())
        .logLevel(Level.BASIC)
        .target(IReCaptchaClient.class, url);

In 8.6.0 call to client.someMethod() returns null with Level.BASIC but works as expected with Level.FULL. No other changes.

**Comment by adriancole** [comment]
wow that sounds less than great.

**Comment by adriancole** [comment]
Not sure what would cause this, as I can't find a change that affects logic that is conditional on log level.. https://github.com/Netflix/feign/compare/v8.5.0...v8.6.0

What is `client.someMethod()` returning?

**Comment by adriancole** [comment]
ahh maybe it is this? 8ee4bd24b0c8c1ccd5ded24d76893c1809febc96

**Comment by adriancole** [comment]
so the response body is rebuffered depending on the log level. https://github.com/Netflix/feign/blob/master/core/src/main/java/feign/SynchronousMethodHandler.java#L102

Maybe there's a situation where inputstream.available() isn't returning a positive number (maybe in okhttp) https://github.com/Netflix/feign/blob/master/jackson/src/main/java/feign/jackson/JacksonDecoder.java#L55

I suspect this is the only place where a bump to v8.6 could make sense in the problem you described. cc @bcrowcs

**Comment by adriancole** [comment]
I'm going to try to reproduce this.

**Comment by adriancole** [comment]
Sorry about this. InputStream.available isn't reliable, so that's what you hit. #253 will fix this and I will quickly release 8.6.1
