### ISSUE TITLE
Memory leak while deploying spring-cloud-netflix application on standalone tomcat

### ISSUE THREAD

**Issue by AsimBiswal** [Netflix/feign#257]
Tomcat fail to stop thread named ServoMonitorGetValueLimiter. 
A thread called ServoMonitorGetValueLimiter started by the the application which is never stopped. This thread is started by  MonitorRegistryMetricPoller of com.netflix.servo . In fact service is failed to stop the thread. The object of this class is a component in ServoMetricCollector of org.springframework.cloud.netflix.servo to exposes servo metrics to the metric endpoint.

when application is undeployed it is unable to unregister the MBean also (com.netflix.servo)

**Comment by adriancole** [comment]
Hehe this is some detective work! Sounds like something implicitly started with ribbon.

**Comment by adriancole** [comment]
might not be important, but which version of feign?

**Comment by AsimBiswal** [comment]
Its ribbon-2.0-RC13

**Comment by spencergibb** [comment]
No need to post this multiple times: https://github.com/spring-cloud/spring-cloud-netflix/issues/491.

**Comment by adriancole** [comment]
will look at this in spring-cloud

**Comment by adriancole** [comment]
seems related to #187

**Comment by spencergibb** [comment]
Spring Cloud uses a [CachingLBClientFactory](https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/feign/ribbon/CachingLBClientFactory.java)
