### ISSUE TITLE
[suggest][notabug] ApacheHttpClient is NOT good for multilingual 

### ISSUE THREAD

**Issue by alphatan** [Netflix/feign#258]
1. Summary

    This is not a bug but a comment to help others suffering the same problem.

    ApacheHttpClient is **NOT** good for multilingual. Suggest using **OkHttpClient** instead.

2. Description

    1. Tested Versions

            feign-core 8.7.1
            feign-jackson 8.7.1
            feign-httpclient 8.7.1
            feign-okhttp 8.7.1

    2. Debug Log (both for ApacheHttpClient and OkHttpClient)

        ---> PATCH http://10.161.128.38:5000/v3/regions/regionOne HTTP/1.1
        Accept: application/json
        X-Auth-Token: 33083e117ff349159707b327dd5eec46
        Content-Type: application/json
        Content-Length: 36

        {"region":{"description":"chinese: '区域';"}}

    3. Actually sent, ApacheHttpClient

            0000   50 41 54 43 48 20 2f 76 33 2f 72 65 67 69 6f 6e  PATCH /v3/region
            0010   73 2f 72 65 67 69 6f 6e 4f 6e 65 20 48 54 54 50  s/regionOne HTTP
            0020   2f 31 2e 31 0d 0a 41 63 63 65 70 74 3a 20 61 70  /1.1..Accept: ap
            0030   70 6c 69 63 61 74 69 6f 6e 2f 6a 73 6f 6e 0d 0a  plication/json..
            0040   58 2d 41 75 74 68 2d 54 6f 6b 65 6e 3a 20 39 62  X-Auth-Token: 9b
            0050   38 61 62 32 37 33 32 39 37 63 34 61 63 31 39 38  8ab273297c4ac198
            0060   37 62 63 33 34 37 34 65 32 33 37 35 35 66 0d 0a  7bc3474e23755f..
            0070   43 6f 6e 74 65 6e 74 2d 54 79 70 65 3a 20 61 70  Content-Type: ap
            0080   70 6c 69 63 61 74 69 6f 6e 2f 6a 73 6f 6e 0d 0a  plication/json..
            0090   43 6f 6e 74 65 6e 74 2d 4c 65 6e 67 74 68 3a 20  Content-Length: 
            00a0   34 33 0d 0a 48 6f 73 74 3a 20 31 30 2e 31 36 31  43..Host: 10.161
            00b0   2e 31 32 38 2e 33 38 3a 35 30 30 30 0d 0a 43 6f  .128.38:5000..Co
            00c0   6e 6e 65 63 74 69 6f 6e 3a 20 4b 65 65 70 2d 41  nnection: Keep-A
            00d0   6c 69 76 65 0d 0a 55 73 65 72 2d 41 67 65 6e 74  live..User-Agent
            00e0   3a 20 41 70 61 63 68 65 2d 48 74 74 70 43 6c 69  : Apache-HttpCli
            00f0   65 6e 74 2f 34 2e 35 20 28 4a 61 76 61 2f 31 2e  ent/4.5 (Java/1.
            0100   38 2e 30 5f 34 35 29 0d 0a 41 63 63 65 70 74 2d  8.0_45)..Accept-
            0110   45 6e 63 6f 64 69 6e 67 3a 20 67 7a 69 70 2c 64  Encoding: gzip,d
            0120   65 66 6c 61 74 65 0d 0a 0d 0a 7b 22 72 65 67 69  eflate....{"regi
            0130   6f 6e 22 3a 7b 22 64 65 73 63 72 69 70 74 69 6f  on":{"descriptio
            0140   6e 22 3a 22 63 68 69 6e 65 73 65 3a 20 27 3f 3f  n":"chinese: '??
            0150   27 3b 22 7d 7d                                   ';"}}

        Note: the two chinese characters '区域' become two actual
        english character '??' (3f3f).

    4. Actually sent, OkHttpClient

            0000   00 ff ec 6d 71 c5 00 ff 2c 08 8a 95 08 00 45 00  ...mq...,.....E.
            0010   01 60 01 5d 40 00 40 06 86 a3 c0 a8 66 28 0a a1  .`.]@.@.....f(..
            0020   80 26 ce 29 13 88 fb a2 ac cb d3 d3 63 36 50 18  .&.)........c6P.
            0030   00 3f 59 f8 00 00 50 41 54 43 48 20 2f 76 33 2f  .?Y...PATCH /v3/
            0040   72 65 67 69 6f 6e 73 2f 72 65 67 69 6f 6e 4f 6e  regions/regionOn
            0050   65 20 48 54 54 50 2f 31 2e 31 0d 0a 41 63 63 65  e HTTP/1.1..Acce
            0060   70 74 3a 20 61 70 70 6c 69 63 61 74 69 6f 6e 2f  pt: application/
            0070   6a 73 6f 6e 0d 0a 58 2d 41 75 74 68 2d 54 6f 6b  json..X-Auth-Tok
            0080   65 6e 3a 20 37 36 30 64 38 32 32 65 62 32 37 34  en: 760d822eb274
            0090   34 61 64 33 62 61 33 62 32 61 36 37 37 39 64 62  4ad3ba3b2a6779db
            00a0   65 35 38 30 0d 0a 43 6f 6e 74 65 6e 74 2d 54 79  e580..Content-Ty
            00b0   70 65 3a 20 61 70 70 6c 69 63 61 74 69 6f 6e 2f  pe: application/
            00c0   6a 73 6f 6e 0d 0a 43 6f 6e 74 65 6e 74 2d 4c 65  json..Content-Le
            00d0   6e 67 74 68 3a 20 34 37 0d 0a 48 6f 73 74 3a 20  ngth: 47..Host: 
            00e0   31 30 2e 31 36 31 2e 31 32 38 2e 33 38 3a 35 30  10.161.128.38:50
            00f0   30 30 0d 0a 43 6f 6e 6e 65 63 74 69 6f 6e 3a 20  00..Connection: 
            0100   4b 65 65 70 2d 41 6c 69 76 65 0d 0a 41 63 63 65  Keep-Alive..Acce
            0110   70 74 2d 45 6e 63 6f 64 69 6e 67 3a 20 67 7a 69  pt-Encoding: gzi
            0120   70 0d 0a 55 73 65 72 2d 41 67 65 6e 74 3a 20 6f  p..User-Agent: o
            0130   6b 68 74 74 70 2f 32 2e 34 2e 30 0d 0a 0d 0a 7b  khttp/2.4.0....{
            0140   22 72 65 67 69 6f 6e 22 3a 7b 22 64 65 73 63 72  "region":{"descr
            0150   69 70 74 69 6f 6e 22 3a 22 63 68 69 6e 65 73 65  iption":"chinese
            0160   3a 20 27 e5 8c ba e5 9f 9f 27 3b 22 7d 7d        : '......';"}}

        Note: the two chinese characters '区域' are now: e58cba e59f9f

    

This issue wasted me 2 whole days. Hope this comment could help others. Maybe some one want to add a WARNING section to the readme.md .

**Comment by adriancole** [comment]
Sounds like a terrible experience. Sorry to hear this. Glad okhttp worked.

I do have a question which is why do you think this is not a bug? Is there
something about apache client that prevents it from ever working with
extended character sets?

**Comment by alphatan** [comment]
I haven't digged enough inside, but just guessed it's not a bug of feign.


For reference, what'd been tried:

1. All java files and working environment are set to UTF-8

2. Append following vm args when starts application (NOT work):

	1. UTF-8

			-Dfile.encoding=UTF-8
			-Dsun.jnu.encoding=UTF-8
			-Dsun.io.unicode.encoding=UnicodeLittle
			-Dfile.encoding.pkg=sun.io

	2. ISO-8859-1

			-Dfile.encoding=ISO-8859-1
			-Dsun.jnu.encoding=ISO-8859-1

3. append 'charset=UTF-8' to  'Content-Type', eg. Content-Type: application/json; charset=UTF-8 (NOT work)

4. config server side. (NOT work)

5. new String

	1. UTF-8, NOT work.

			new String("区域".getBytes(), "UTF-8")

	2. ISO-8859-1, **WORKED but UGLY**.

			new String("区域".getBytes(), "ISO-8859-1")

		This solution is too ugly, considered as 'The Last Solution';

6. change ApacheHttpClient to OkHttpClient (**WORKED PERFECTLY**)

**Comment by adriancole** [comment]
Great info. Thanks for sharing!
