### ISSUE TITLE
@Param fails to pick up expansion of @Headers on interface

### ISSUE THREAD

**Issue by stromnet** [Netflix/feign#262]
Hi,

I'm experimenting with @Headers on the interface class, rather than each individual method. In my case I want an "Authorization: xxx" header which should be populated at each call:
```
@Headers("Authorization: {authHeader}")
public interface SomeApi {
        @RequestLine("GET /someobj?match={match}")
        List<SomeObj> getSomeObj(@Param("match") String match, @Param("authHeader") String authHeader);
}
```

It seems the Default Contract implementation will first process annotations on all methods, including @Param annotations, and then it will process annotations on the interface. During the analyze of @Param annotations it does not find the {authHeader} in the headers() (since it has not yet been processed), and thus adds it as a formParam.

During execution it will fail, when it uses BuildFormEncodedTemplateFromArgs, and no body is specified (same as #259).

Expected: that it would map the @Param to the @Headers on the interface.
Workaround: Move the @Headers annotation to each method.

**Comment by adriancole** [comment]
Looks like a bug to me. Thanks for reporting (and giving a workaround).

Want to give a try at fixing it?

**Comment by stromnet** [comment]
Any reason for doing headersFromAnnotation in Default contract and not in base contract? If no specific reason, would it make sense to call headersFromAnnotation the same way that  'processAnnotationOnMethod' is called?

**Comment by adriancole** [comment]
It was an attempt to not break compatibility since there are third-party
implementors of Contract. I recall that @jdamick had a nice design in
general for when we want to break contract (no pun intended).

**Comment by stromnet** [comment]
Could something like the following cut it, without breaking breaking compatibility?

Pseudo-patch:
```    
class BaseContract:

+protected void headersFromAnnotation(Class<?> targetType, MethodMetadata data) {
+}

protected MethodMetadata parseAndValidateMetadata(Class<?> targetType, Method method) {
      MethodMetadata data = new MethodMetadata();
      data.returnType(Types.resolve(targetType, targetType, method.getGenericReturnType()));
      data.configKey(Feign.configKey(targetType, method));
+     headersFromAnnotation(method.getDeclaringClass(), data);
+     if (method.getDeclaringClass() != targetType) {
+        headersFromAnnotation(targetType, data);
+     }
      for (Annotation methodAnnotation : method.getAnnotations()) {
        processAnnotationOnMethod(data, methodAnnotation, method);
      }
      checkState(data.template().method() != null,
                 "Method %s not annotated with HTTP method type (ex. GET, POST)",
                 method.getName());
      Class<?>[] parameterTypes = method.getParameterTypes();

```
```
class Default extends BaseContract {

-  @Override
-    protected MethodMetadata parseAndValidateMetadata(Class<?> targetType, Method method) {
-      MethodMetadata data = super.parseAndValidateMetadata(targetType, method);
-      headersFromAnnotation(method.getDeclaringClass(), data);
-      if (method.getDeclaringClass() != targetType) {
-        headersFromAnnotation(targetType, data);
-      }
-      return data;
-    }

-    private void headersFromAnnotation(Class<?> targetType, MethodMetadata data) {
+    @Override
+    protected void headersFromAnnotation(Class<?> targetType, MethodMetadata data) {

```

Thus, for Default, headersFromAnnotation will be called a bit earlier. For any others, a no-op function will be called unless overridden.

**Comment by adriancole** [comment]
Sounds like a plan!

I'd rename it to `processAnnotationOnClass(MethodMetadata data, Class<?> class)` and document that this will be called for the declaring class of the method, then the target type. I might also look for an opportunity to optimize the jaxrs one, which probably is the case.

**Comment by jdamick** [comment]
Yeah that's similar to where i was heading.

For ref if helps: https://github.com/jdamick/feign/commit/49a67401f2fe0cb1e4e14262f18df02d83ecbda8

**Comment by adriancole** [comment]
My 2p is that when we want to make a breaking change.. Continue on that

**Comment by stromnet** [comment]
Fix merged, issue resolved. Closing.
