### ISSUE TITLE
Body Expansion Incorrectly "Decoding" Unencoded Values?

### ISSUE THREAD

**Issue by ddteeter** [Netflix/feign#264]
Question/possible issue here.

Attempting to do a POST with a very simple body expansion and it seems like there's an issue line with the RequestTemplate body expansion.  Specifically here:

`body(urlDecode(expand(bodyTemplate, unencoded)));`

It seems like urlDecoding unencoded parameters can cause issues with certain strings.  For instance, if I have a '+' character in the argument being substituted, the urlDecode would swap the '+' for ' ' (this is the case I'm running into).  I imagine you would run into issues with '%<...>' in substituted strings as well.

I can't get my head around why just using `encoded`, the already encoded map, here wouldn't be the right solution.  It would expand into a fully encoded string (including anything encoded in the body template) and then properly decode to the full body.  

Is there a simple way to work around this during Feign building?  Swapping out the RequestTemplate for one that does the correct encoding doesn't seem very tenable -- looks like you'd have to swap all the way out in the contract and dupe a fair amount of code, since the RequestTemplate is instantiated inline with the MethodMetadata, and MethodMetadata is instantiated inline in the BaseContract.  Anything obvious I'm missing here?

**Comment by adriancole** [comment]
I think you are suggesting a change to the implementation of RequestTemplate, particularly around encoding as they relate to http bodies. Bear in mind that feign has a single `Param` type for anywhere expansion could occur (including the request line, which is the normal case).

If you know a way to preserve existing functionality, and also help with the encoding woes on unencoded params by reworking RequestTemplate, go for it! We have pretty good coverage on the related area, so start with a failing test? Even if you can't put time into fixing an impl, pasting a failing test back here would help.

**Comment by ddteeter** [comment]
Failing Test, in RequestTemplateTest:
````
@Test
public void resolveTemplateWithBodyTemplateDoesNotDoubleDecode() {
    RequestTemplate template = new RequestTemplate().method("POST")
        .bodyTemplate(
            "%7B\"customer_name\": \"{customer_name}\", \"user_name\": \"{user_name}\", " +
                "\"password\": \"{password}\"%7D");

    template = template.resolve(
        mapOf(
            "customer_name", "netflix",
            "user_name", "denominator",
            "password", "abc+123%25d8"
        )
    );

    assertThat(template)
        .hasBody(
            "{\"customer_name\": \"netflix\", \"user_name\": \"denominator\", \"password\": \"abc+123%25d8\"}");
}
````

Fails with the following:
````
Expected :"{"customer_name": "netflix", "user_name": "denominator", "password": "abc+123%25d8"}"
Actual   :"{"customer_name": "netflix", "user_name": "denominator", "password": "abc 123%d8"}"
````

Proposed change, currently line 232 of RequestTemplate:
````
public RequestTemplate resolve(Map<String, ?> unencoded) {
    ...
    if (bodyTemplate != null) {
      body(urlDecode(expand(bodyTemplate, unencoded)));
    }
    ...
}
````
Replace with:
````
public RequestTemplate resolve(Map<String, ?> unencoded) {
    ...
    if (bodyTemplate != null) {
      body(urlDecode(expand(bodyTemplate, encoded)));
    }
    ...
}
````

The encoded params already exist (used for expansion in the URL).  All pasts look to test for me after this change.  I may be missing something obvious here on cases where this wouldn't work.

**Comment by adriancole** [comment]
Looks like it is pull request time!  Tell you what.. I'll run denominator's
tests off your PR's branch.. if they fail, we are missing a test.
Otherwise, let's get your change in (complete with the new test!)

Good hunting, Drew!
