### ISSUE TITLE
Add support for @Consumes annotations at TypeLevel

### ISSUE THREAD

**Issue by fritzrichter** [Netflix/feign#272]
Currently I have to annotate every single method in my interface with a @Consume annotation, I would like to define the default @Consume at the Type Level and annotating the entire Interface. Feign, unfortunately does not take that annotation into account.

**Comment by adriancole** [comment]
I think this is a dupe. can you try feign 8.10.0? https://github.com/Netflix/feign/commit/995ef2ade0e7ff4fb721dd83d70d4452bd11c570
