### ISSUE TITLE
Awkward error when header parameter isn't at index 0

### ISSUE THREAD

**Issue by adriancole** [Netflix/feign#301]
There's a pretty awkward error when someone attempts to do Bearer token directly.

Given
```java
@RequestLine("GET /me/tracks?offset={offset}&limit={limit}")
@Headers("Authorization: Bearer {access_token}")
List<Track> tracks(@Param("access_token") String accessToken, @Param("offset") Integer offset, @Param("limit") Integer limit);
```

We throw this:
```
feign.codec.EncodeException: class java.util.LinkedHashMap is not a type supported by this encoder.

    at feign.codec.Encoder$Default.encode(Encoder.java:84)
    at feign.ReflectiveFeign$BuildFormEncodedTemplateFromArgs.resolve(ReflectiveFeign.java:227)
    at feign.ReflectiveFeign$BuildTemplateByResolvingArgs.create(ReflectiveFeign.java:199)
    at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:70)
    at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:94)
    at com.sun.proxy.$Proxy97.tracks(Unknown Source)
```

We could do a better job in the associated logic, ex. throw an error instead of assuming it is a form. Ex. in above it is a GET, so we could harden this logic: https://github.com/Netflix/feign/blob/v8.12.1/core/src/main/java/feign/Contract.java#L246

Thanks to @backfx for reporting

See #288 on oauth and the more general issue

**Comment by MattFriedman** [comment]
I'm struggling with the issue right now. 

Seems to me having two params for @Headers such as key and value would possibly help with this issue.

**Comment by adriancole** [comment]
We've gotten a lot of miles without breaking api on Headers. Probably first step is making the error better.

**Comment by cesartl** [comment]
Hi, Is there a workaround for this issue? How can I set a Bearer token directly?

**Comment by adriancole** [comment]
This should already work, as the code's been merged here https://github.com/Netflix/feign/pull/326/files#diff-ce1202871042b955135cdebcd2233cd4R377

**Comment by cesartl** [comment]
Yes sorry. Updated to latest version and it worked.
Thanks
