### ISSUE TITLE
Mix of query-parameters and body not possible?

### ISSUE THREAD

**Issue by fritzrichter** [Netflix/feign#310]
Hey together, the following API contract is given by an external provider (we HAVE to implement this).

   @Headers("Content-Type: application/json")
   @RequestLine("/member-data-sharing?id={sharingId}")
   SingleSharingResponse updateSharing(@Param("sharingId") Long sharingId, MemberDataSharing sharing);

So I have a QueryParam and I need to send a JSON Object via PUT as body.

I get the following Exception: "Body parameters cannot be used with form parameters." from Contract.java.

How can I solve this?

**Comment by adriancole** [comment]
@fritzrichter sounds like a problem! Mind validating by adding a failing test to DefaultContractTest? The failure is not likely to do with json, more the contract parsing itself.

My guess is there's something subtle about how this is dealing with query parameters. To validate this.. try renaming your variable to "id" which would match the query key.

**Comment by fritzrichter** [comment]
That does not really help, see the code of the Contract.java:
```
      Annotation[][] parameterAnnotations = method.getParameterAnnotations();
      int count = parameterAnnotations.length;
      for (int i = 0; i < count; i++) {
        boolean isHttpAnnotation = false;
        if (parameterAnnotations[i] != null) {
          isHttpAnnotation = processAnnotationsOnParameter(data, parameterAnnotations[i], i);
        }
        if (parameterTypes[i] == URI.class) {
          data.urlIndex(i);
        } else if (!isHttpAnnotation) {
          checkState(data.formParams().isEmpty(),
                     "Body parameters cannot be used with form parameters.");
          checkState(data.bodyIndex() == null, "Method has too many Body parameters: %s", method);
          data.bodyIndex(i);
          data.bodyType(Types.resolve(targetType, targetType, method.getGenericParameterTypes()[i]));
        }
      }
      return data;
    }
```
It seems, that I can not mix QueryParams and body objects together with Feign, which is of course not a good approach, but I as the developer need to implement the external API anyway, so feign should not prohibit that right?

**Comment by adriancole** [comment]
sorry it didn't help. I wouldn't jump to conclusions about things being
explicitly prohibited etc. I really think there's something subtle here vs
some draconian contract.

patience! I'll have a look later today and do what I pasted (make a failing
test.. figure out why)

**Comment by adriancole** [comment]
It was indeed subtle! The annotation is RequestLine, not Path.. add "GET"!

```
@RequestLine("GET /member-data-sharing?id={sharingId}")
```

I fixed the error message, so the next release will have a nicer message in this case. I'm so sorry as indeed this was a subtle issue that stole an unnecessary amount of your time.

#311

**Comment by fritzrichter** [comment]
Oh no :) so simple, of course i totally missed that... Thanks a lot for your help! This actually saved my time :)
