### ISSUE TITLE
Feign fails if static methods are not annotated

### ISSUE THREAD

**Issue by j-baker** [Netflix/feign#312]
Hi,
Java 8 allows static methods on interfaces. The way I want to use this is to slightly remove boilerplate - instead of having an interface, and a static creator for it somewhere else, I'd ideally like to have the static creator inside the interface, like

    public interface Foo {
        @RequestLine("GET foo")
        String getFoo();

        @RequestLine("GET bar")
        String getBar(@Param("baz") Baz baz);

        static Foo create(String url, Feign.Builder builder) {
            builder.encoder(new FooEncoder());
            return builder.attach(Foo.class, url);
        }
    }

This (with Feign) requires the method to be annotated with a @RequestLine and @Params, like

    @RequestLine("GET IDoNotThinkThisShouldBeHere")
    static Foo create(@Param("NeitherHere") String url, @Param("NorHere") Feign.Builder builder) {
        builder.encoder(new FooEncoder());
        return builder.attach(Foo.class, url);
    }

Feign validates that the method is annotated correctly, even though any Feign implementation can never be called (as it is static). I think that Feign should ignore static methods on interfaces. The primary drawback of this is that it would be untestable - presumably the test suite must run on Java versions <= 8, where no implementation could compile.

I'd be happy to code this up if it sounds reasonable?

**Comment by adriancole** [comment]
A number of projects I'm on allow the test tree to compile java 8, though I
don't know how to do this in gradle. If you are up to task, the feature you
mention sounds quite cool.

**Comment by oillio** [comment]
Along the same lines, I would also like feign to ignore default methods.
The use case I am thinking about is to implement convenience methods that make it easier for code to use the API.  For instance:
```
public interface Foo {
    @RequestLine("GET foo")
    List<String> getFoo(@Param("startDate") Long startDate, @Param("endDate") Long endDate);

    default List<String> getFoo(DateTime start, DateTime end) {
        return getFoo(start.getMillis(), end.getMillis());
    } 
}
```

I don't think there is any viable reason to want Feign to handle default methods, and I would be surprised if it worked anyway.
Unless there are objections, I would be happy to code up ignoring static and default methods in the next couple days.  I will take a crack at moving the tests to java 8 as well.

**Comment by adriancole** [comment]
I think the challenge is more or less how to do this without making feign
require source level 8 features. Before you do a pull request, do you have
an approach in mind to this?

I don't know what default methods look like from a reflection POV vs other
methods.

**Comment by oillio** [comment]
Yeah, I looked into it further and you are right.  I can detect default methods without a problem (they are public, non-abstract, non-synthetic methods on an interface).  However, I can't find an easy way to invoke it from the proxy.
The new MethodHandler functionality can do it, if Feign is ever upgraded to Java 7 or later.
On Java 6, I would need to do byte code manipulation, which is a bit heavy handed for such a small feature.

I will submit a pull request to support ignoring static methods, which was easy enough to implement.

I have one request; would it be acceptable to ignore default methods in the Contract, in the same way I implemented ignoring static methods?  This would allow me to implement support for default methods by writing my own InvocationHandler in Java 8.
The current error message about missing annotations doesn't really make sense for this edge case anyway.  If you want, I could throw in a more descriptive error in the InvocationHandler.

If this is acceptable, I can throw that in my PR as well.

**Comment by adriancole** [comment]
yeah, seems sensible to ignore default methods in the contract.

I'd add the comments about limitations on proxy and java 7+ to the
invocation handler, and cross-reference the existing issue about moving to
java 7 language level.

On that note, I don't think there was any resistance about moving to
language level 7. it only impacts certain versions of android, and even
utilities like okhttp and retrofit use level 7 these days. You could
implement a bump to level 7, which could make this change easier.
