### ISSUE TITLE
Explain FeignClient -> Eureka service name resolution

### ISSUE THREAD

**Issue by macheeto** [Netflix/feign#315]
Hello,
Could you explain how FeignClient knows which service registered with Eureka is the right one for it?
I saw a couple of issues which I thought might be caused by client not being able to locate the corresponding service provider (TimeoutException: null, or message about load balancer not finding service).
While FeignClient works with URLs:
@FeignClient(name = "abc", url = "http://localhost:8094")
public interface MyClient {
@RequestMapping(method = RequestMethod.GET, value = "/data/ids")
List<Response> getDataByIds(@RequestParam("ids") String[] ids);
}
I was not yet able to tell it to connect to service by Eureka service name lookup.
I guess my question is "if service is registered with Eureka under my-service name, how do you tell FeignClient to look it up by that name (my-service)"?
Thanks!

Marcin

**Comment by spencergibb** [comment]
Wrong issue tracker. https://github.com/spring-cloud/spring-cloud-netflix/issues
