### ISSUE TITLE
Example of POM/dependency tree that allows FeignClient to use configuration property

### ISSUE THREAD

**Issue by macheeto** [Netflix/feign#316]
Hello,
I have another question. I ran into jar compatibility issues while trying to add security interceptor for FeignClient (basic auth or oauth). It seems that only milestone versions contain "configuration" property in FeignClient annotation:
spring-cloud-netflix-core, version 1.1.0.M4
When I add this to my POM file which is otherwise using release Spring jars I get exceptions at startup, for example:
IllegalStateException: Error processing condition on org.springframework.cloud.netflix.eureka.EurekaDiscoveryClientConfiguration$EurekaHealthIndicatorConfiguration.eurekaHealthIndicator
IllegalArgumentException: @ConditionalOnMissingBean annotations must specify at least one bean (type, name or annotation)

It seems that definition provided in spring-boot-autoconfigure jar differs from the one used in Eureka code?
I would appreciate it if you could provide a dependency list that solves this problem.
Thanks,

Marcin

**Comment by spencergibb** [comment]
Wrong issue tracker https://github.com/spring-cloud/spring-cloud-netflix/issues
