### ISSUE TITLE
Support multiple inheritance in Contract

### ISSUE THREAD

**Issue by jebeaudet** [Netflix/feign#320]
We're using Feign for inter-services calls in a micro services architecture. We would like to move to a single interface between the client and the resource so that changes in the api are reflected automatically to the client. 

The problem is that some clients we built during the past months extends 2 specific interfaces related to common tasks between the micro services (backup related actions for instance).

While trying to refactor the code, I hit the (understandable) limitation of the single inheritance. I'd be open to work on that and make a PR out of it, is this something you'd consider merging? I know I can provide my own `Contract` but I'd like to have your opinion on contributing this upstream first.

I haven't thought about all the details yet but it would be something like scanning all the extended interfaces and making sure that all the methods defined have the proper metadata.

Thanks!

**Comment by adriancole** [comment]
Hi, Jacques.

There are bound to be edge cases I'm can't think up at the moment. I'm
hesitant about a formal feature for multiple inheritance.. it is tricky to
get right, and the bug surface area in the most core code would be greater.

You'll notice we tend to lazy-implement difficult features, and that
usually it is surrounded by multiple parties requesting the same thing.
This is the sort of a rule-of-three
<http://blog.codinghorror.com/rule-of-three/> approach, which puts onus on
folks to find others who have the same needs (either directly, or
indirectly by waiting for people to express interest on the issue).

More concretely, I'd recommend trying this out on your fork, or as a
sub-project. Often there are bugs and such around features like this that
take time to smoke out. By creating a solid implementation, and posting a
link to it here, it is more likely others can try it and lobby for that to
be an upstream feature.

**Comment by jebeaudet** [comment]
Hi Adrian,

Thanks for getting back to me. It'll help in the decision we take how we'll refactor our clients into a single interface model. If we decide to try the multiple inheritance way, I'll try on my fork and share the results here as you suggested.

Thanks for the lib! I'll close this one for now and reopen if necessary.

**Comment by qinfchen** [comment]
@jebeaudet what did you guys end up doing?

**Comment by jebeaudet** [comment]
Nothing yet, we haven't upgraded our Feign version and we most likely won't
in the near future. Sorry, let me know if you implement it I'd be
interested!

**Comment by Jardo-51** [comment]
We also ran into the single-inheritance problem yesterday. So I guess you have 2 out of 3 requests :)

**Comment by iolkhovskyy** [comment]
Unfortunately, we have very similar problem using openfeign, caused by multiple level of inheritance. It looks right now like BaseAPI<T> -> API -> Feign / Controller, and results in test error, or memory leak in some situations.

**Comment by dezelvol** [comment]
Unfortunately, we have very similar problem using openfeign, caused by multiple level of inheritance. It looks right now like BaseAPI<T> -> API -> Feign / Controller, and results in test error, or memory leak in some situations.

**Comment by velo** [comment]
If you could provide one test that reproduces the problem, it can try to give a shot on fixing it.

**Comment by dezelvol** [comment]
To reproduce this issue you can create new project on start.spring.io, only with feign dependency.
Then create three interfaces:
`public interface Interface1 {
}`
`@RequestMapping("/")
public interface Interface2 extends Interface1 {
    @GetMapping("/get")
    public void get();
}`
`@FeignClient(name = "my-client", url = "localhost:8080")
public interface MyFeignClient extends Interface2 {
}`

And test:
`@RunWith(SpringRunner.class)
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.DEFINED_PORT)
public class DemoApplicationTests {
    @Autowired
    MyFeignClient myFeignClient;
	@Test
	public void contextLoads() {
        this.myFeignClient.get();
	}
}`

Test will fail with error:
`org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'com.example.demo.DemoApplicationTests': Unsatisfied dependency expressed through field 'myFeignClient'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.example.demo.MyFeignClient': FactoryBean threw exception on object creation; nested exception is java.lang.IllegalStateException: Only single-level inheritance supported: MyFeignClient`

With single interface inheritance it works well. 
One way to fix this is elimination of multi-layer inheritance, but we are extending generic GRUD api's with project related functionality so it would be nice to stick with this solution.

**Comment by dezelvol** [comment]
My friend shared code snippet that actually works. It has on issue - you have to duplicate method variable mapping in children. Except this code works fine.

You need to create Hierarchical contract bean in your configuration, to make it working.

[HierarchicalContract.txt](https://github.com/OpenFeign/feign/files/2699276/HierarchicalContract.txt)

**Comment by gab-fin** [comment]
It would be great to support it, we have a hierarchy of interfaces and it represents a lot of work/duplication to flatten it out. I believe that this is request 3 :-).
