### ISSUE TITLE
Empty body should not be decoded as JSON

### ISSUE THREAD

**Issue by stevemayhew** [Netflix/feign#321]
Feign turns a 200 success response with an empty body into an exception.  The problem is that Synchronous method  executeAndDecode does not check the response body exists or content length header before calling decode here: https://github.com/Netflix/feign/blob/master/core/src/main/java/feign/SynchronousMethodHandler.java#L129

While returning empty might not be the best API, many do it.  Turning this into a null object return would be perfectly acceptable.

**Comment by adriancole** [comment]
on the "While returning empty might not be the best API, many do it." bit..
can you cite any public apis that return 200 and empty body instead of 404?
I've never seen one, but agree it could exist. If this is internal stuff,
I'd probably ask them to change and make a wrapping decoder until that
happens.

**Comment by adriancole** [comment]
ps the reason why decode doesn't check the body is that it can build an object from http headers. I'm assuming the exception came from a gson or jackson decoder?

One way around your issue could be to write a wrapping decoder which does what you are looking for. 

Ex.
```java
class NullOnNoContentDecoder {
    Decoder delegate = new GsonDecoder();

    @Override
    public Object decode(Response response, Type type) throws IOException {
      if (response.body() == null) return null;
      return delegate.decode(response, type);
    }
  }
```

If we get more nods on the idea of making no bodies default to null.. happy to re-open. Hope the above helps for now.
