### ISSUE TITLE
NPE when @Path is first on a method 

### ISSUE THREAD

**Issue by peterwippermann** [Netflix/feign#327]
I'm trying to setup a REST client:
`Feign.builder().contract(new JAXRSContract()).encoder(new JacksonEncoder()).decoder(new JacksonDecoder()).target(RESTService.class, "http://...");`

Then I get the following exception:

> java.lang.NullPointerException: method of /api
> 	at feign.Util.checkNotNull(Util.java:104)
> 	at feign.Request.<init>(Request.java:47)
> 	at feign.Request.create(Request.java:36)
> 	at feign.RequestTemplate.request(RequestTemplate.java:241)
> 	at feign.RequestTemplate.toString(RequestTemplate.java:551)
> 	at feign.jaxrs.JAXRSContract.processAnnotationOnMethod(JAXRSContract.java:93)
> 	at feign.Contract$BaseContract.parseAndValidateMetadata(Contract.java:92)
> 	at feign.jaxrs.JAXRSContract.parseAndValidateMetadata(JAXRSContract.java:50)
> 	at feign.Contract$BaseContract.parseAndValidatateMetadata(Contract.java:61)
> 	at feign.ReflectiveFeign$ParseHandlersByName.apply(ReflectiveFeign.java:137)
> 	at feign.ReflectiveFeign.newInstance(ReflectiveFeign.java:55)
> 	at feign.Feign$Builder.target(Feign.java:198)
> 	at feign.Feign$Builder.target(Feign.java:194)
> 	at (my code...)

The error seems to have been known before, as there was already a patch for this:
https://github.com/Netflix/feign/commit/4dbbdb7e149cd771abaddf5349feae946cadd7c1

However, it was only included in v8.13.0. But it was overwritten with the old code in v8.13.1 again!? Could you please patch it again? :-/

**Comment by adriancole** [comment]
it didn't end up being cherry-picked!

**Comment by adriancole** [comment]
8.14.4 on the way. sorry about that!

**Comment by peterwippermann** [comment]
Great support! Thank you very much, @adriancole :-)
