### ISSUE TITLE
Can not deserialize instance of rx.Observable

### ISSUE THREAD

**Issue by fiunchinho** [Netflix/feign#331]
I run into an exception trying to implement the example from the documentation. You can see the problem in this gist https://gist.github.com/fiunchinho/c250427a2bb0186786c9

The problem occurs trying to make the feign client return an rx.Observable. I assumed that it'd automatically subscribe some decoder to my observable so it could decode the object emitted by the observable. It works fine if I switch the signature from Observable to List, but I'd like to use it asynchronously.

 Is there a way to subscribe an encoder so I can keep the asynchronous call?

**Comment by spencergibb** [comment]
You need to use the `HystrixFeign` builder to get Observable support

**Comment by fiunchinho** [comment]
That worked. Thank you!

**Comment by adriancole** [comment]
Thanks.. Good eye, Spencer!

**Comment by netzwerg** [comment]
This did not work for me when returning a `Observable<Contributor>`. I had to return a `Observable<List<Contributor>>` and `flatMap` over it later (see https://github.com/netzwerg/feign-rxjava-jackson/blob/65aae414c7ec7659614cc18c17e7fbef0e74b37d/src/main/java/ch/netzwerg/feign/GitHubClientDemo.java).

Am I missing something?

**Comment by adriancole** [comment]
Yep the result of the app call is a single-value (of a list) . You could
use the new static method support  to flatmap implicitly  unroll a list
result.

-A

**Comment by netzwerg** [comment]
Thanks Adrian, good to know!

**Comment by timbog** [comment]
What do I have to do if I use spring-cloud-starter-openfeign and get the same error? https://stackoverflow.com/questions/56183536/feignclient-from-openfeign-and-observable-leads-to-fasterxml-jackson-databind-e
