### ISSUE TITLE
NullPointerException in HystrixInvocationHandler when calling hashCode, equals or toString of proxy

### ISSUE THREAD

**Issue by sfussenegger** [Netflix/feign#332]
`HystrixInvocationHandler` should handle those methods just like `ReflectiveFeign.FeignInvocationHandler`, i.e. check for these methods before calling `HystrixInvocationHandler.this.dispatch.get(method).invoke(args);`

**Comment by adriancole** [comment]
agreed

**Comment by mpegram3rd** [comment]
I'd definitely love to see this issue fixed.... Is there a matching issue over on the Hystrix Core issues list?

**Comment by mpegram3rd** [comment]
Created an issue on the Hystrix repo: [https://github.com/Netflix/Hystrix/issues/1178](https://github.com/Netflix/Hystrix/issues/1178)

**Comment by mattrjacobs** [comment]
Can I get some more context on this issue?  (Feel free to reply here or on Netflix/Hystrix#1178).

Specifically, can you direct me to some Feign code that demonstrates this behavior?  I haven't seen this when using Hystrix directly, so that would be very helpful.  Thanks!

**Comment by sfussenegger** [comment]
If I remember correctly the context was during spring initialization with spring-cloud etc. But I think the context isn't that important. It's obvious from looking at the [code of HystrixInvocationHandler](https://github.com/Netflix/feign/blob/master/hystrix/src/main/java/feign/hystrix/HystrixInvocationHandler.java#L68) that every invocation of `hashCode()`, `equlas(..)` and `toString()` will cause an NPE (my comments in all caps):

    HystrixCommand<Object> hystrixCommand = new HystrixCommand<Object>(setter) {
      @Override
      protected Object run() throws Exception {
        try {
          // NPE - NO OBJECT METHODS IN DISPATCH
          return HystrixInvocationHandler.this.dispatch.get(method).invoke(args);
        } catch (Exception e) {
          throw e;
        } catch (Throwable t) {
          throw (Error) t;
        }
      }

      @Override
      protected Object getFallback() {
        // SNIP
      }
    };

The reason is that the `Map<Method, MethodHandler> dispatch` [explicitly excludes methods defined by `Object`](https://github.com/Netflix/feign/blob/master/core/src/main/java/feign/ReflectiveFeign.java#L58):

    for (Method method : target.type().getMethods()) {
      if (method.getDeclaringClass() == Object.class) {
        continue; // OBJECT EXCLUDED
      } else if(Util.isDefault(method)) {
       // SNIP
       methodToHandler.put(method, handler);
      } else {
        methodToHandler.put(method, nameToHandler.get(Feign.configKey(target.type(), method)));
      }
    }

as I wrote in when I opened this ticket, [the implementation of `ReflectiveFeign.FeignInvocationHandler`](https://github.com/Netflix/feign/blob/master/core/src/main/java/feign/ReflectiveFeign.java#L88) is a good reference:

    public Object invoke(Object proxy, Method method, Object[] args) throws Throwable {
      if ("equals".equals(method.getName())) {
        try {
          Object
              otherHandler =
              args.length > 0 && args[0] != null ? Proxy.getInvocationHandler(args[0]) : null;
          return equals(otherHandler);
        } catch (IllegalArgumentException e) {
          return false;
        }
      } else if ("hashCode".equals(method.getName())) {
        return hashCode();
      } else if ("toString".equals(method.getName())) {
        return toString();
      }
      // OBJECT METHODS SEPARATELY
      return dispatch.get(method).invoke(args);
    }

_(I would normally submit a PR myself but the Eclipse Gradle plugin sucks. Simply getting the project set up just takes too much time)_

**Comment by mattrjacobs** [comment]
@sfussenegger Is there a change that you think Hystrix should make, or is the fix purely within Feign?

**Comment by sfussenegger** [comment]
the bug is in `feign.hystrix.HystrixInvocationHandler` which is in `feign-hystrix`

**Comment by mattrjacobs** [comment]
Thanks @sfussenegger, that's what it looked like to me as well, just wanted to make sure I wasn't missing anything.  I'm going to close https://github.com/Netflix/Hystrix/issues/1178

**Comment by mpegram3rd** [comment]
Gentlemen, thanks for the closer review here and re-narrowing the focus of the issue.  My apologies for the cross bug post.  I should've looked a little closer at the origin of the class in question.

**Comment by adriancole** [comment]
seems this issue has a clear fix and just looking for someone to make pull request. I'll be that someone

**Comment by adriancole** [comment]
fix here https://github.com/Netflix/feign/pull/380

**Comment by adriancole** [comment]
on the way as v8.16.1
