### ISSUE TITLE
Testing with Eureka

### ISSUE THREAD

**Issue by micheal-swiggs** [Netflix/feign#358]
I'm just wondering if there are any examples of how to test Eureka based feign clients for a microservice architecture? I have tests that make calls to other services. At the moment these break as I get `java.lang.RuntimeException: com.netflix.client.ClientException: Load balancer does not have available server for client: service-name`. Do I need to use `eureka.client.enabled: false` ?

**Comment by adriancole** [comment]
I'd ask on spring-cloud-netflix, as I bet you'd find yourself closer to an
answer! I know they have a lot of experience in eureka integration.

**Comment by padilo** [comment]
I was looking for the same, the answer is here:
https://github.com/spring-cloud/spring-cloud-netflix/issues/906
