### ISSUE TITLE
Consider creating a feign-plugins (or feign-extesions) repo for contributions

### ISSUE THREAD

**Issue by dgomesbr** [Netflix/feign#359]
Just got carried by the conversation in the [feign gitter channel ](https://gitter.im/Netflix/feign) and since I started to consider using and really using feign, one thing I was amazed and also pissed off was it's simplicity. While highly configurable, things that was convenient on other frameworks like Spring MVC (Request Mapping, MethodHandlerInterceptor), pass a context data do every request that could be populated or mutated depending of the the request made and so on wasn't available so easy on feign.

@adriancole and other fellow maintainers are going light speed with the contributions, but I don't think we should limit to that. My proposal is that we follow (or at least discuss so we can improve this idea) the ELK (elastic search actually) model where you have the [main repo](https://github.com/logstash) and the [contrib one](https://github.com/logstash-plugins)

I'm not really sure how we should maintain a compatibility matrix for that, my personal opinion goes labeling a GA(release version) as base and having strictly rules for those repos on the plugins, so we could keep bumping feign versions and running build pipelines for those plugins againt the main version.

Apart from that, I'm not that familiar on how feign is open for composition, decoration and so on, but for that idea flourish and succeed we're probably gonna need rework a few details here and there.

So, after that, let's start the discussion :dart: 

For example 
Avro-decoder from @davidmc24 - https://github.com/commercehub-oss/feign-extensions

**Comment by dgomesbr** [comment]
Some of @jmnarloch https://github.com/jmnarloch/feign-vnderror-spring-cloud-starter and https://github.com/jmnarloch/feign-oauth2-spring-cloud-starter could be extracted as well.

**Comment by spencergibb** [comment]
I started something like that fit Spring Cloud https://github.com/spring-cloud-incubator

**Comment by adriancole** [comment]
lets merge this with #373
