### ISSUE TITLE
Throw NullPointException when response code is 422

### ISSUE THREAD

**Issue by ooeyuna** [Netflix/feign#371]
some restful api maybe return error http code like "401","403","422", but `HttpURLConnection` cannot Identify error http code except `404 Not Found`,it makes `feign.Response.<init>` throw NullPointException  at `checkNotNull(reason, "reason")`

stack:
```
java.lang.NullPointerException: reason
        at feign.Util.checkNotNull(Util.java:104) ~[feign-core-8.12.1.jar:8.12.1]
        at feign.Response.<init>(Response.java:49) ~[feign-core-8.12.1.jar:8.12.1]
        at feign.Response.create(Response.java:60) ~[feign-core-8.12.1.jar:8.12.1]
```

**Comment by adriancole** [comment]
this should be fixed in latest feign

**Comment by xyalan** [comment]
I have the same error.

**Comment by adriancole** [comment]
@xyalan please update to a more recent version of feign, as this was indeed addressed a while back https://github.com/Netflix/feign/blob/8.x/core/src/main/java/feign/Response.java#L49
