### ISSUE TITLE
Method to remove extra headers sent by feign

### ISSUE THREAD

**Issue by ADeane6** [Netflix/feign#372]
I'm running feign in spring with spring security when calling the endpoint which in-turn calls a service which uses feign Gson

EndPoint:

     @ApiOperation(value = "Cisco 1000v", notes = "Used with Nexus 1000v to Get configuration")
     @RequestMapping(value = "/cisco", method = RequestMethod.GET)
    public String getCisco(
             @ApiParam(value = "Function to apply to switch", required = true)   @RequestParam(value="Function") String function,
             @ApiParam(value = "Hostname of device", required = true) @RequestParam(value="host")  String hostname,
             @ApiParam(value = "Username for device login", required = true) @RequestParam(value="user") String username,
             @ApiParam(value = "Password of device", required = true) @RequestParam(value="pass")   String password) throws IOException, SAXException, ParserConfigurationException {

        CiscoNexus service = new CiscoNexus(hostname, username, password);
        if (function.equals("port-profile")) {
            return service.getPort();`

Service:

    public class CiscoNexus {
    
    private final String hostname, username, password;

    public CiscoNexus(String hostname, String username, String password) {
        this.hostname = hostname;
        this.username = username;
        this.password = password;
    }
    public String getPort() {
        PortProfiles ports = Feign.builder()
                .decoder(new GsonDecoder())
                .encoder(new GsonEncoder())
                .target(PortProfiles.class, "http://" + username + ":" + password + "@" + hostname);

        System.out.println("Getting Port Profiles...");
        ports.json();
        return ports.json();
    }

    interface PortProfiles {
        @RequestLine("GET /api/port-profile")
        @Headers("Accept: application/json")
        string json();
    }

As I'm using spring security when I call the endpoint I have to add an auth header, but it seems feign keeps the header and sends it on to the target which doesn't respond correctly because of it, is this something that can be avoided?

The Error I'm receiving

    {
      "timestamp": 1459964595082,
      "status": 500,
      "error": "Internal Server Error",
      "exception": "feign.FeignException",
      "message": "status 401 reading PortProfiles#json(); content:\n<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n<html><head>\n<title>401 Authorization Required</title>\n</head><body>\n<h1>Authorization Required</h1>\n<p>This server could not verify that you\nare authorized to access the document\nrequested.  Either you supplied the wrong\ncredentials (e.g., bad password), or your\nbrowser doesn't understand how to supply\nthe credentials required.</p>\n</body></html>\n",
      "path": "/switch/cisco"
    }

**Comment by adriancole** [comment]
Please open this in spring-cloud-netflix because any change or advice
involves classes not present in this repository
