### ISSUE TITLE
Support for @SerializedName in GsonDecoder

### ISSUE THREAD

**Issue by ztuit** [Netflix/feign#378]
Hi,
I have encountered an issue decoding the response if the JSON key names contain hyphens '-'.

Usually this could be solvable via the @SerializedName annotation, but this doesn't appear to be available in feign.gson.GsonDecoder.

Trying to import GSON where the annotation is defined causes incompatibilities with the GsonDecoder: 

**Exception in thread "main" java.lang.IncompatibleClassChangeError: class feign.gson.DoubleToIntMapTypeAdapter has interface com.google.gson.TypeAdapter as super class.**

Is there a plan to add support for this annotation anytime soon? If not is there a better workaround for this other than ditching the GSONDecoder and doing it manually, or by writing a custom decoder?

Many thanks,

**Comment by adriancole** [comment]
GsonDecoder has a couple constructors. For example, you can provide your own Gson, which is configured exactly how you like https://github.com/Netflix/feign/blob/master/gson/src/main/java/feign/gson/GsonDecoder.java#L45
