### ISSUE TITLE
feign.Client throws Invalid HTTP when connecting to a Tomcat Ver 9.x server

### ISSUE THREAD

**Issue by kk-manh** [Netflix/feign#382]
Class feign.Client expects both a HTTP Status Code and a valid HTTP Response Message.
Specifically on line number 155 .. snippet below

 `Response convertResponse(HttpURLConnection connection) throws IOException {
      int status = connection.getResponseCode();
      String reason = connection.getResponseMessage();
      if (status < 0 || reason == null) { `

This causes "Invalid HTTP.." exception to be thrown when connecting to a REST Service running on Tomcat Version 9.  Tomcat 9 has dropped support for Http Response message.
This works fine in Tomcat 8.x

**Comment by adriancole** [comment]
this is a big problem in any service that uses http/2. fixing right away.

**Comment by adriancole** [comment]
here's the fix. thanks for reporting this!

https://github.com/Netflix/feign/pull/383

**Comment by kk-manh** [comment]
Adrian,
Thank you for the fix.
