### ISSUE TITLE
Custom ErrorDecoder wraps Exception in java.lang.reflect.UndeclaredThrowableException

### ISSUE THREAD

**Issue by flash1293** [Netflix/feign#386]
I tried to implement a custom error-decoder, but Feign doesn't throw the Exception returned by the decoder but a java.lang.reflect.UndeclaredThrowableException which wraps my custom exception:
```
//...
.errorDecoder(new ErrorDecoder() {
                    @Override
                    public Exception decode(String methodKey, Response response) {
                        if (response.status() == 404) {
                            return new NotFoundException("product not found");
                        }
                        return errorStatus(methodKey, response);
                    }
                })
//...
try {
   apiProxy.getStuff();
} catch(Throwable t) {
//t is java.lang.reflect.UndeclaredThrowableException, but should be NotFoundException
}
```

Is this really the desired behaviour? I expected to see my own exception-class thrown at this point.

**Comment by adriancole** [comment]
is the exception you are throwing checked?

**Comment by flash1293** [comment]
This was the problem, thanks a lot! If I declare NotFoundException as unchecked, it is returned correctly. Is this somewhere documented and I just missed it? I'm not that experienced in Java, maybe this is obvious, but it should still be documented here: https://github.com/Netflix/feign/wiki/Custom-error-handling

**Comment by Hronom** [comment]
+1 here, this should be documented!

In the experimental way I found that you can also use checked exception not wrapped in `java.lang.reflect.UndeclaredThrowableException`.

For this you need to include checked exception in the interface of feign client, example:

```java
public class MyBadRequestException extends Exception {
    public MyBadRequestException(String body) {
        super(body);
    }
}
```

```java
public class MyErrorDecoder implements ErrorDecoder {

    private final ErrorDecoder defaultErrorDecoder = new Default();

    @Override
    public Exception decode(String methodKey, Response response) {
        if (response.status() >= 400 && response.status() <= 499) {
            try {
                byte[] bodyData = Util.toByteArray(response.body().asInputStream());
                String responseBody = new String(bodyData);
                return new MyBadRequestException(responseBody);
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
        return defaultErrorDecoder.decode(methodKey, response);
    }
}
```

```java
@FeignClient(value = "test-service", decode404 = true)
public interface TestServiceClient {
    @PostMapping(value = "/testItems", consumes = MediaTypes.HAL_JSON_VALUE)
    ResponseEntity<Resource<TestItem>> create(TestItem testItem) throws MyBadRequestException;

    @GetMapping(value = "/testItems", consumes = MediaTypes.HAL_JSON_VALUE)
    ResponseEntity<Resources<TestItem>> findAll() throws MyBadRequestException;

    @GetMapping(value = "/testItems/{id}", consumes = MediaTypes.HAL_JSON_VALUE)
    ResponseEntity<Resource<TestItem>> findOne(@PathVariable("id") String id) throws MyBadRequestException;
}
```

It seems that this related to Java behaviour:
https://stackoverflow.com/questions/5490139/getting-undeclaredthrowableexception-instead-of-my-own-exception
https://docs.oracle.com/javase/7/docs/api/java/lang/reflect/UndeclaredThrowableException.html

**Comment by akshayhiremath-rogers** [comment]
To make the custom exception unchecked just extend RuntimeException in your custom exception class instead of Exception class. :-)
