### ISSUE TITLE
Dynamic url support

### ISSUE THREAD

**Issue by madgnome** [Netflix/feign#395]
Does feign support passing dynamic url like retrofit does? 

https://futurestud.io/blog/retrofit-2-how-to-use-dynamic-urls-for-requests

**Comment by adriancole** [comment]
Closest we have is use a parameter of type URI. This will substitute for
any base url.

**Comment by buckett** [comment]
This is useful when wanting the handle paging in clients that return URLs in their responses for pagination. The example in `RequestLine` is:

    @RequestLine("GET")
    Response getNext(URI nextLink);
