### ISSUE TITLE
Potential XXE in SAXDecoder

### ISSUE THREAD

**Issue by gursev** [Netflix/feign#411]
An XXE issue exists with the way xmlReader is used in the SAXDecoder class.

```
public class SAXDecoder implements Decoder {

  private final Map<Type, ContentHandlerWithResult.Factory<?>> handlerFactories;

  private SAXDecoder(Map<Type, ContentHandlerWithResult.Factory<?>> handlerFactories) {
    this.handlerFactories = handlerFactories;
  }

  public static Builder builder() {
    return new Builder();
  }

  @Override
  public Object decode(Response response, Type type) throws IOException, DecodeException {
    if (response.status() == 404) return Util.emptyValueOf(type);
    if (response.body() == null) return null;
    ContentHandlerWithResult.Factory<?> handlerFactory = handlerFactories.get(type);
    checkState(handlerFactory != null, "type %s not in configured handlers %s", type,
               handlerFactories.keySet());
    ContentHandlerWithResult<?> handler = handlerFactory.create();
    try {
      XMLReader xmlReader = XMLReaderFactory.createXMLReader();
      xmlReader.setFeature("http://xml.org/sax/features/namespaces", false);
      xmlReader.setFeature("http://xml.org/sax/features/validation", false);
      xmlReader.setContentHandler(handler); **// XXE**
      InputStream inputStream = response.body().asInputStream();
      try {
        xmlReader.parse(new InputSource(inputStream));
      } finally {
        ensureClosed(inputStream);
      }
      return handler.result();
    } catch (SAXException e) {
      throw new DecodeException(e.getMessage(), e);
    }
  }

```
Recommendation: Consider setting the following three features to false
1. http://xml.org/sax/features/external-general-entities
2. http://xml.org/sax/features/external-parameter-entities
3. http://apache.org/xml/features/disallow-doctype-decl
4. http://apache.org/xml/features/nonvalidating/load-external-dtd

**Comment by gursev** [comment]
@adriancole can you guys look into it? and possibly assign it a security tag?

**Comment by adriancole** [comment]
feign is run by volunteers, and you've already opened a bug. We don't have
a special "security bug" feature. Plus, sax is a niche functionality which
most don't use.

Since you discovered this, and detailed what to do... why not raise a pull
request and help?

**Comment by adriancole** [comment]
also, like all code, if there's some way to create a unit test showing
this works, please do. eye-balling things isn't great assurance for
anything. Finally, if there are some compensating concerns, for
example, this is obviated when X system properties, or only possible
when dynamic classes are loaded etc. that would help, too.

Reason I mention this is that not everyone will understand the
criticality or impact if we just say "XXE!" despite it being an old
attack.

Here's an example:

Based on https://www.owasp.org/index.php/XML_External_Entity_(XXE)_Processing

An attacker intercepts performs a MITM attack and returns a fake XML
response which is still valid from a schema POV. When a field is being
read by a custom parser, maybe that holds an entity tag instead. So,
for example if that field was holding an ID, perhaps it ends up with
the contents of some file the application has access to read. The
attacker is able to control feign, to read that parsed value or a
parse exception including it.

I suspect this also affects the more often used JAXB support
(feign-jaxb), so whoever addresses this could also use the same tests
there.

http://stackoverflow.com/questions/12977299/prevent-xxe-attack-with-jaxb

**Comment by gursev** [comment]
@adriancole I'll be happy to issue a pull request for the fix. Won't be able to write unit tests at this time. Let me know if that works.

**Comment by adriancole** [comment]
sure.. I can help with the unit test part.

**Comment by gursev** [comment]
@adriancole thank you
