### ISSUE TITLE
Named Query Parameters on GET requests

### ISSUE THREAD

**Issue by devmop** [Netflix/feign#85]
Picking up the latest version I'd expect to be able to do something like the following

@RequestLine("GET /users?name={name}")
public JsonObject getUsersByName(@Named("name") String name);

Unfortunately this doesn't seem to work. The default encoder receives a LinkedHashMap and complains about it not being a String. The GsonEncoder copes fine with it but the end result is that a POST is made with the query parameters encoded into the body.

**Comment by adriancole** [comment]
this has been released. Note 7.1.0 is releasing today, which implies transitioning from `@Named` to `@Param` which supports custom parameter expansion.
