### ISSUE TITLE
Provide easier support for empty targets

### ISSUE THREAD

**Issue by davidmc24** [Netflix/feign#98]
In some cases, it may be useful to have Feign instances that don't have any base URL at all.  Instead, all methods would include a URI parameter.

Currently, this can be accomplished by using a custom implementation of Target that requires a URL to be provided.  I've included an example below.  This target can then be passed to `Feign.builder().target(Target)` `Feign.create(Target, Object...)`.

If such an EmptyTarget were included in feign-core, we could add signatures like `Feign.builder().target(Class)` that allow creating Feign instances without a base URL and without explicitly specifying a Target type.  A signature for `Feign.create` will require a bit more thought, since `Feign.create(Class, Object...)` would conflict with the pre-existing `Feign.create(Class, String, Object...)`.

```java
public class EmptyTarget<T> implements Target<T> {
    private final Class<T> type;
    private final String name;

    public EmptyTarget(Class<T> type) {
      this.type = checkNotNull(type, "type");
      this.name = "empty:" + type.getSimpleName();
    }

    @Override
    public Class<T> type() {
        return type;
    }

    @Override
    public String name() {
        return name;
    }

    @Override
    public String url() {
        throw new UnsupportedOperationException("Empty targets don't have URLs");
    }

    @Override
    public Request apply(RequestTemplate input) {
        if (input.url().indexOf("http") != 0) {
            throw new UnsupportedOperationException("Request with non-absolute URL not supported with empty target");
        }
        return input.request();
    }

    @Override
    public int hashCode() {
        return Arrays.hashCode(new Object[]{type, name});
    }

    @Override
    public boolean equals(Object obj) {
      if (obj == null) {
          return false;
      }
      if (this == obj) {
          return true;
      }
      if (EmptyTarget.class != obj.getClass()) {
          return false;
      }
      EmptyTarget<?> that = EmptyTarget.class.cast(obj);
      return this.type.equals(that.type) && this.name.equals(that.name);
    }
}
```

**Comment by adriancole** [comment]
Looks sensible

**Comment by adriancole** [comment]
on the way.. https://github.com/Netflix/feign/pull/157
